[[pages]]
path = "interface/Home.py"
name = "CarlitosDB - PÃ¡gina Inicial"
icon = "ğŸ–¥ï¸"

[[pages]]
path = "interface/pages/Funcionarios.py"
name = "Funcionarios"
icon = "ğŸ‘©â€ğŸ’¼"

[[pages]]
path = "interface/pages/Atendentes.py"
name = "Atendentes"
icon = "ğŸ“"

[[pages]]
path = "interface/pages/Motoqueiros.py"
name = "Motoqueiros"
icon = "ğŸ›µ"

[[pages]]
path = "interface/pages/Gerentes.py"
name = "Gerentes"
icon = "ğŸ‘¨â€ğŸ’¼"

[[pages]]
path = "interface/pages/Clientes.py"
name = "Clientes"
icon = "ğŸ‘¥"

[[pages]]
path = "interface/pages/Alimentos.py"
name = "Alimentos"
icon = "ğŸ”"

[[pages]]
path = "interface/pages/Pedidos.py"
name = "Pedidos"
icon = "ğŸ›’"
